name: my_todo_list
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1


environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  get: ^4.7.2
  iconsax: ^0.0.8
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/todo_logo.svg
    - assets/todo_icon.png
  
